# snapcraft.yaml - builds a Snap package of the Apache Maven build tool
# Copyright 2021 John Neffenger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: mymaven
title: My Maven
summary: Apache Maven for the OpenJDK Snap
description: |
  Apache Maven is a build automation tool used primarily for Java
  projects. Maven can also be used to build and manage projects
  written in C#, Ruby, Scala, and other languages.

  This package provides the Maven build tool for Linux and uses the
  OpenJDK Snap package, if installed, when the JAVA_HOME environment
  variable is not set. Building this package downloads the Maven source
  code directly from the Apache Web site, verifies its SHA-512 hash
  value, and builds Maven from source.

  For more information, see the repository for this package on GitHub:

  https://github.com/jgneff/mymaven

  Java and OpenJDK are trademarks or registered trademarks of Oracle
  and/or its affiliates.

version: '3.8.3'
license: Apache-2.0

base: core18
grade: stable
confinement: classic

architectures:
- build-on: amd64
  run-on: all

apps:
  mymaven:
    command: bin/maven.sh

parts:
  bin:
    plugin: dump
    source: .
    stage: [bin]

  maven:
    plugin: nil
    source: https://downloads.apache.org/maven/maven-3/${SNAPCRAFT_PROJECT_VERSION}/source/apache-maven-${SNAPCRAFT_PROJECT_VERSION}-src.tar.gz
    source-checksum: sha512/7d7b6abf8f0407f95e35ccf857412b59c8ebfa0b2eef8cf52badf20d47e4be1e79f2412965d514314240184847b5bf5c20e63c7f4b8d6cce5d2f3bc5bd31d2f2
    build-packages: [maven]
    override-build: |
      # Gets the host and port from a proxy URL
      #   $1 = the proxy URL, such as "http://10.10.10.1:8222/"
      getproxy () {
          host=$(echo "$1" | sed -E 's|https?://([^:/]*):?[0-9]*/?|\1|')
          port=$(echo "$1" | sed -E 's|https?://[^:/]*:?([0-9]*)/?|\1|')
      }

      # Sets Java networking properties when using a proxy server
      if [ -n "${http_proxy:-}" ]; then
          getproxy "$http_proxy"
          http="-Dhttp.proxyHost=$host -Dhttp.proxyPort=$port"
      fi
      if [ -n "${https_proxy:-}" ]; then
          getproxy "$https_proxy"
          https="-Dhttps.proxyHost=$host -Dhttps.proxyPort=$port"
      fi

      # Builds Maven
      export MAVEN_OPTS="$http $https"
      mvn -DdistributionTargetDir="$SNAPCRAFT_PART_INSTALL/maven" \
          -Dmaven.buildNumber.skip=true \
          --batch-mode --strict-checksums --quiet install
